apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJjR1YwY25CaGRteHZkamN4TURwbmFIQmZVemRvVm1JMFZXbG9NMDkyY0dsRFNEUkxUbWRXVkc0MlFrUktaRGgwTUZKV2R6bEkiCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
